### ISSUE TITLE
TypeScript compilation error "Statements are not allowed in ambient contexts" with v9.0.0

### ISSUE THREAD

**Issue by kpala** [quantizor/markdown-to-jsx#731]
After upgrading to v9.0.0, I'm getting the following TS compilation error:

```
../node_modules/markdown-to-jsx/dist/react.d.ts:292:2 - error TS1036: Statements are not allowed in ambient contexts.

292  {}
     ~
```

My usage is simply:

```ts
import Markdown from 'markdown-to-jsx/react';

<Markdown ... />
```

**Comment by quantizor** [comment]
Fix will be out shortly, thanks and sorry about that https://github.com/quantizor/markdown-to-jsx/pull/732

**Comment by kpala** [comment]
Excellent, thanks for the quick fix!
